In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
x = [ 2, 1, 0, -1, -2, -1, 0 ,1, 2 , 1 ,0, -1] # Analog sine wave input
y = [ 1, 1, 0, -1 , -1 , -1  ,0, 1, 1, 1 , 0 , -1] # digital output
layer1 = keras.layers.Dense(1, activation=tf.nn.relu)
# ReLU=> y=x, if x >0, y=0, if x <=0

model = keras.models.Sequential([layer1])
model.compile(loss= keras.losses.mae, optimizer='adam', metrics=[keras.metrics.mean_squared_error])

In [3]:
model.fit(x,y,epochs=100, verbose=0)
predictions = model.predict(x)
print(predictions)

[[2.7832463]
 [1.3416232]
 [0.       ]
 [0.       ]
 [0.       ]
 [0.       ]
 [0.       ]
 [1.3416232]
 [2.7832463]
 [1.3416232]
 [0.       ]
 [0.       ]]


In [4]:
model.get_weights()
# trainable_params = input_size * output_size + output_size
# 1 X 1 + 1= 2
# regression neural network

[array([[1.4416231]], dtype=float32), array([-0.09999993], dtype=float32)]

In [18]:
x = [ 2, 1, 0, -1, -2, -1, 0 ,1, 2 , 1 ,0, -1] # Analog sine wave input
y = [ 1, 1, 0, -1 , -1 , -1  ,0, 1, 1, 1 , 0 , -1] # digital output
layer1 = keras.layers.Dense(2)
# ReLU=> y=x, if x >0, y=0, if x <=0
# 0 and 1 -> should be 0th position < 1st position, or vice versa 
model = keras.models.Sequential([layer1])
model.compile(loss= keras.losses.mae, optimizer='adam', metrics=[keras.metrics.mean_squared_error])

In [19]:
model.fit(x,y,epochs=100, verbose=0)
predictions = model.predict(x)
#print(predictions)
# First output-> for positives, 1st position-> negative
for prediction in predictions:
  if prediction[0] > prediction[1]:
    print('positive')
  if prediction[0] < prediction[1]:
    print('negative')
  if prediction[0] == prediction[1]:
    print('zero')

positive
positive
zero
negative
negative
negative
zero
positive
positive
positive
zero
negative


In [20]:
predictions[2]

array([-9.650776e-05, -9.650776e-05], dtype=float32)

In [21]:
predictions

array([[-2.0035083e+00, -2.5379686e+00],
       [-1.0018024e+00, -1.2690326e+00],
       [-9.6507763e-05, -9.6507763e-05],
       [ 1.0016093e+00,  1.2688395e+00],
       [ 2.0033152e+00,  2.5377755e+00],
       [ 1.0016093e+00,  1.2688395e+00],
       [-9.6507763e-05, -9.6507763e-05],
       [-1.0018024e+00, -1.2690326e+00],
       [-2.0035083e+00, -2.5379686e+00],
       [-1.0018024e+00, -1.2690326e+00],
       [-9.6507763e-05, -9.6507763e-05],
       [ 1.0016093e+00,  1.2688395e+00]], dtype=float32)

In [ ]:
# users provide 2 entities:
# input set -> parameters
# output set [if missing-> unsupervised learning!]
# anything modified by developers-> hyperparameter
# no. of output dimensions-> i was manipulating!
# loss functions, optimizer functions-> i was adjusting 
# EPOCHS-> how many iterations?