In [1]:
# Agenda-> Neural Networks
# Tensorflow
# TF 2.x 

# Computer Vision
# Natural LP
# SIGNAL 

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.5.0'

In [15]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8, 9 ,10])
y = np.array([0,1,0,1,0,1,0,1,0,1])

In [16]:
from tensorflow import keras


In [17]:
layer1 = keras.layers.Dense(1)
model = keras.models.Sequential([layer1])
model.compile(loss= keras.losses.mean_squared_error, optimizer='adam', metrics=[keras.metrics.mean_squared_error])

In [30]:
history = model.fit(x, y, epochs=50)

Epoch 1/50
1/1 [==============================] - 0s 469ms/step - loss: 98.2729 - mean_squared_error: 98.2729
Epoch 2/50
1/1 [==============================] - 0s 5ms/step - loss: 98.1324 - mean_squared_error: 98.1324
Epoch 3/50
1/1 [==============================] - 0s 6ms/step - loss: 97.9920 - mean_squared_error: 97.9920
Epoch 4/50
1/1 [==============================] - 0s 5ms/step - loss: 97.8517 - mean_squared_error: 97.8517
Epoch 5/50
1/1 [==============================] - 0s 4ms/step - loss: 97.7115 - mean_squared_error: 97.7115
Epoch 6/50
1/1 [==============================] - 0s 5ms/step - loss: 97.5715 - mean_squared_error: 97.5715
Epoch 7/50
1/1 [==============================] - 0s 6ms/step - loss: 97.4315 - mean_squared_error: 97.4315
Epoch 8/50
1/1 [==============================] - 0s 3ms/step - loss: 97.2917 - mean_squared_error: 97.2917
Epoch 9/50
1/1 [==============================] - 0s 5ms/step - loss: 97.1519 - mean_squared_error: 97.1519
Epoch 10/50
1/1 [=========

In [34]:
history.history['loss']

[98.27290344238281,
 98.13240051269531,
 97.99201965332031,
 97.85172271728516,
 97.7115478515625,
 97.57147216796875,
 97.4315185546875,
 97.29167175292969,
 97.15194702148438,
 97.01233673095703,
 96.87284088134766,
 96.73345947265625,
 96.59419250488281,
 96.45504760742188,
 96.31602478027344,
 96.1771240234375,
 96.0383529663086,
 95.89973449707031,
 95.76119995117188,
 95.62281799316406,
 95.48456573486328,
 95.34644317626953,
 95.20845031738281,
 95.07059478759766,
 94.9328842163086,
 94.7952880859375,
 94.65784454345703,
 94.52052307128906,
 94.38335418701172,
 94.2463150024414,
 94.10941314697266,
 93.97264862060547,
 93.8360366821289,
 93.69956970214844,
 93.56321716308594,
 93.4270248413086,
 93.29098510742188,
 93.15507507324219,
 93.0193099975586,
 92.88370513916016,
 92.74821472167969,
 92.6128921508789,
 92.47769927978516,
 92.34265899658203,
 92.20774841308594,
 92.072998046875,
 91.93838500976562,
 91.8039321899414,
 91.66962432861328,
 91.53545379638672]

In [35]:
model.summary()
# y = w1 * x + bias
# trainable params-> 2 

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [36]:
model.get_weights()

[array([[-1.4677981]], dtype=float32), array([0.04977656], dtype=float32)]

In [37]:
predictedvalues = model.predict(x)


In [38]:
predictedvalues

array([[ -1.4180216],
       [ -2.8858197],
       [ -4.3536177],
       [ -5.821416 ],
       [ -7.289214 ],
       [ -8.757011 ],
       [-10.22481  ],
       [-11.692608 ],
       [-13.160406 ],
       [-14.628204 ]], dtype=float32)

In [43]:
layer1 = keras.layers.Dense(10)
layer2 = keras.layers.Dense(1)
model = keras.models.Sequential([layer1, layer2])
model.compile(loss= keras.losses.mean_squared_error, optimizer='adam', metrics=[keras.metrics.mean_squared_error])

In [44]:
history = model.fit(x, y, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 309ms/step - loss: 0.7321 - mean_squared_error: 0.7321
Epoch 2/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6819 - mean_squared_error: 0.6819
Epoch 3/100
1/1 [==============================] - 0s 4ms/step - loss: 0.6347 - mean_squared_error: 0.6347
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 0.5907 - mean_squared_error: 0.5907
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 0.5497 - mean_squared_error: 0.5497
Epoch 6/100
1/1 [==============================] - 0s 4ms/step - loss: 0.5118 - mean_squared_error: 0.5118
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 0.4771 - mean_squared_error: 0.4771
Epoch 8/100
1/1 [==============================] - 0s 6ms/step - loss: 0.4455 - mean_squared_error: 0.4455
Epoch 9/100
1/1 [==============================] - 0s 18ms/step - loss: 0.4170 - mean_squared_error: 0.4170
Epoch 10/100
1/1 [================

In [45]:
model.summary()
# broken numbers

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 10)                20        
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 11        
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [46]:
y = model.predict(x)

In [47]:
y

array([[0.11859248],
       [0.19123855],
       [0.26388434],
       [0.33653045],
       [0.40917653],
       [0.48182225],
       [0.5544684 ],
       [0.62711436],
       [0.69976044],
       [0.7724067 ]], dtype=float32)

In [48]:
# 3 Layer- Fully Connected- Neural Network
layer1 = keras.layers.Dense(8)
layer2 = keras.layers.Dense(256)
layer3 = keras.layers.Dense(1)
model = keras.models.Sequential([layer1, layer2, layer3])
model.compile(loss= keras.losses.mean_squared_error, optimizer='adam', metrics=[keras.metrics.mean_squared_error])

In [49]:
history = model.fit(x, y, epochs=100, verbose=0) # dont show output here
predictions = model.predict(x)
predictions


array([[0.11706932],
       [0.18881647],
       [0.2605638 ],
       [0.33231103],
       [0.4040585 ],
       [0.47580552],
       [0.54755294],
       [0.61930007],
       [0.69104725],
       [0.76279473]], dtype=float32)

In [51]:
print(model.get_weights())

[array([[ 0.66135097, -0.70871294,  0.76123554, -0.47558627,  0.58221865,
        -0.43693173,  0.78388596, -0.14149727]], dtype=float32), array([-4.8985989e-03,  1.3297434e-03, -1.0850670e-02, -8.9848872e-05,
       -3.6856446e-03,  4.7660465e-03, -1.7078320e-02,  1.5977845e-02],
      dtype=float32), array([[-0.06729606, -0.12439454, -0.05957604, ..., -0.08307312,
         0.03362969, -0.06543975],
       [-0.06178607,  0.13898404, -0.14185952, ..., -0.08565797,
        -0.11954904, -0.11333348],
       [ 0.14789945,  0.12843531,  0.15190567, ...,  0.11687102,
        -0.10910536,  0.07225763],
       ...,
       [-0.02841901, -0.06888364,  0.03974408, ..., -0.07482613,
        -0.05112453,  0.04523912],
       [-0.1354391 ,  0.1475518 , -0.06271402, ...,  0.01279932,
        -0.07863083,  0.04103004],
       [ 0.00487382,  0.10472643,  0.09283444, ...,  0.03729657,
         0.08030588, -0.08074294]], dtype=float32), array([ 0.00235625,  0.00090538,  0.0019563 ,  0.00238551,  0.00182