In [1]:
import tensorflow as tf
import numpy as np

In [4]:
rawcorpus = "Richie Rich is poor. Uncle Scrooje is rich. Pikachu is hungry. He and Pikachu are both blue. All uncles are green."

In [5]:
# Lower-> nouns
# deduplications-> set()
words = []
for word in rawcorpus.lower().split():
  if word != '.': # independent symbol
    word = word.replace('.','')
    words.append(word)


In [11]:
print(words)
print(len(words))
# Sequence
#training data

['richie', 'rich', 'is', 'poor', 'uncle', 'scrooje', 'is', 'rich', 'pikachu', 'is', 'hungry', 'he', 'and', 'pikachu', 'are', 'both', 'blue', 'all', 'uncles', 'are', 'green']
21


In [9]:
uniquewords = set(words)
print(uniquewords)
print(len(uniquewords))
# bag of words

{'green', 'uncles', 'scrooje', 'rich', 'he', 'richie', 'pikachu', 'uncle', 'and', 'are', 'blue', 'hungry', 'poor', 'both', 'is', 'all'}
16


In [12]:
# set for dictionary-> conv to numbers
# label encoding 
word2int = {}
int2word = {}
vocab_size = len(uniquewords)

In [13]:
for i,word in enumerate(uniquewords):
  word2int[word] = i
  int2word[i] = word


In [14]:

print(word2int)
print(int2word)

{'green': 0, 'uncles': 1, 'scrooje': 2, 'rich': 3, 'he': 4, 'richie': 5, 'pikachu': 6, 'uncle': 7, 'and': 8, 'are': 9, 'blue': 10, 'hungry': 11, 'poor': 12, 'both': 13, 'is': 14, 'all': 15}
{0: 'green', 1: 'uncles', 2: 'scrooje', 3: 'rich', 4: 'he', 5: 'richie', 6: 'pikachu', 7: 'uncle', 8: 'and', 9: 'are', 10: 'blue', 11: 'hungry', 12: 'poor', 13: 'both', 14: 'is', 15: 'all'}


In [15]:
print(word2int['both'])
print(int2word[3])

13
rich


In [16]:
rawsentences = rawcorpus.split('.')
sentences = []
for sentence in rawsentences:
  sentences.append(sentence)

In [18]:
sentences # extra element in the end-> remove it

['Richie Rich is poor',
 ' Uncle Scrooje is rich',
 ' Pikachu is hungry',
 ' He and Pikachu are both blue',
 ' All uncles are green',
 '']

In [19]:
sentences = sentences[:-1]
sentences

['Richie Rich is poor',
 ' Uncle Scrooje is rich',
 ' Pikachu is hungry',
 ' He and Pikachu are both blue',
 ' All uncles are green']

In [35]:
# word pairs
# autocomplete: 1-1 pair
windowsize = 2 # 1X2 window
data = []

# in below loop, i am taking, +2 ahead window-> when my loop is no last word, second last word-> i will get an exception.
# sentence-> less than 2 words? 
# sentence-> 1 word-> word, pair-> will become same word!
for sentence in sentences:
  allwordsinsentence = sentence.split()
  for i,word in enumerate(allwordsinsentence):
    for nxtword in allwordsinsentence[max(i-windowsize,0) : min(i+windowsize, len(sentence)+1) ]:
      if word!=nxtword:
        data.append([word.lower(), nxtword.lower()])



In [36]:
print(data)

[['richie', 'rich'], ['rich', 'richie'], ['rich', 'is'], ['is', 'richie'], ['is', 'rich'], ['is', 'poor'], ['poor', 'rich'], ['poor', 'is'], ['uncle', 'scrooje'], ['scrooje', 'uncle'], ['scrooje', 'is'], ['is', 'uncle'], ['is', 'scrooje'], ['is', 'rich'], ['rich', 'scrooje'], ['rich', 'is'], ['pikachu', 'is'], ['is', 'pikachu'], ['is', 'hungry'], ['hungry', 'pikachu'], ['hungry', 'is'], ['he', 'and'], ['and', 'he'], ['and', 'pikachu'], ['pikachu', 'he'], ['pikachu', 'and'], ['pikachu', 'are'], ['are', 'and'], ['are', 'pikachu'], ['are', 'both'], ['both', 'pikachu'], ['both', 'are'], ['both', 'blue'], ['blue', 'are'], ['blue', 'both'], ['all', 'uncles'], ['uncles', 'all'], ['uncles', 'are'], ['are', 'all'], ['are', 'uncles'], ['are', 'green'], ['green', 'uncles'], ['green', 'are']]


In [37]:
def Encoder(idx, vocabsize):
  temp = np.zeros(vocabsize) # cold sequence
  # ENCODING MAP
  temp[idx] = 1 # hot sequence 
  return temp
# input-> 000001000000000
# output-> 0000000001000000


In [38]:
trainx = []
trainy = []
for wordpair in data:
  try:
    trainx.append(Encoder(word2int[wordpair[0]], vocabsize= vocab_size))
    trainy.append(Encoder(word2int[wordpair[1]], vocabsize= vocab_size))
  except:
    trainx.pop()
    continue

In [39]:
len(trainx)

43

In [40]:
len(trainy)

43

In [41]:
trainx[:5]

[array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]),
 array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.])]

In [42]:
trainy[:2]

[array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])]