In [1]:
# Agenda-> Neural Networks
# Tensorflow
# TF 2.x 

# Computer Vision
# Natural LP
# SIGNAL 

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'2.5.0'

In [15]:
import numpy as np
x = np.array([1,2,3,4,5,6,7,8, 9 ,10])
y = np.array([0,1,0,1,0,1,0,1,0,1])

In [16]:
from tensorflow import keras


In [17]:
layer1 = keras.layers.Dense(1)
model = keras.models.Sequential([layer1])
model.compile(loss= keras.losses.mean_squared_error, optimizer='adam', metrics=[keras.metrics.mean_squared_error])

In [30]:
history = model.fit(x, y, epochs=50)

Epoch 1/50
1/1 [==============================] - 0s 469ms/step - loss: 98.2729 - mean_squared_error: 98.2729
Epoch 2/50
1/1 [==============================] - 0s 5ms/step - loss: 98.1324 - mean_squared_error: 98.1324
Epoch 3/50
1/1 [==============================] - 0s 6ms/step - loss: 97.9920 - mean_squared_error: 97.9920
Epoch 4/50
1/1 [==============================] - 0s 5ms/step - loss: 97.8517 - mean_squared_error: 97.8517
Epoch 5/50
1/1 [==============================] - 0s 4ms/step - loss: 97.7115 - mean_squared_error: 97.7115
Epoch 6/50
1/1 [==============================] - 0s 5ms/step - loss: 97.5715 - mean_squared_error: 97.5715
Epoch 7/50
1/1 [==============================] - 0s 6ms/step - loss: 97.4315 - mean_squared_error: 97.4315
Epoch 8/50
1/1 [==============================] - 0s 3ms/step - loss: 97.2917 - mean_squared_error: 97.2917
Epoch 9/50
1/1 [==============================] - 0s 5ms/step - loss: 97.1519 - mean_squared_error: 97.1519
Epoch 10/50
1/1 [=========

In [34]:
history.history['loss']

[98.27290344238281,
 98.13240051269531,
 97.99201965332031,
 97.85172271728516,
 97.7115478515625,
 97.57147216796875,
 97.4315185546875,
 97.29167175292969,
 97.15194702148438,
 97.01233673095703,
 96.87284088134766,
 96.73345947265625,
 96.59419250488281,
 96.45504760742188,
 96.31602478027344,
 96.1771240234375,
 96.0383529663086,
 95.89973449707031,
 95.76119995117188,
 95.62281799316406,
 95.48456573486328,
 95.34644317626953,
 95.20845031738281,
 95.07059478759766,
 94.9328842163086,
 94.7952880859375,
 94.65784454345703,
 94.52052307128906,
 94.38335418701172,
 94.2463150024414,
 94.10941314697266,
 93.97264862060547,
 93.8360366821289,
 93.69956970214844,
 93.56321716308594,
 93.4270248413086,
 93.29098510742188,
 93.15507507324219,
 93.0193099975586,
 92.88370513916016,
 92.74821472167969,
 92.6128921508789,
 92.47769927978516,
 92.34265899658203,
 92.20774841308594,
 92.072998046875,
 91.93838500976562,
 91.8039321899414,
 91.66962432861328,
 91.53545379638672]

In [35]:
model.summary()
# y = w1 * x + bias
# trainable params-> 2 

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 1)                 2         
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [36]:
model.get_weights()

[array([[-1.4677981]], dtype=float32), array([0.04977656], dtype=float32)]

In [37]:
predictedvalues = model.predict(x)


In [38]:
predictedvalues

array([[ -1.4180216],
       [ -2.8858197],
       [ -4.3536177],
       [ -5.821416 ],
       [ -7.289214 ],
       [ -8.757011 ],
       [-10.22481  ],
       [-11.692608 ],
       [-13.160406 ],
       [-14.628204 ]], dtype=float32)

In [43]:
layer1 = keras.layers.Dense(10)
layer2 = keras.layers.Dense(1)
model = keras.models.Sequential([layer1, layer2])
model.compile(loss= keras.losses.mean_squared_error, optimizer='adam', metrics=[keras.metrics.mean_squared_error])

In [44]:
history = model.fit(x, y, epochs=100)

Epoch 1/100
1/1 [==============================] - 0s 309ms/step - loss: 0.7321 - mean_squared_error: 0.7321
Epoch 2/100
1/1 [==============================] - 0s 5ms/step - loss: 0.6819 - mean_squared_error: 0.6819
Epoch 3/100
1/1 [==============================] - 0s 4ms/step - loss: 0.6347 - mean_squared_error: 0.6347
Epoch 4/100
1/1 [==============================] - 0s 4ms/step - loss: 0.5907 - mean_squared_error: 0.5907
Epoch 5/100
1/1 [==============================] - 0s 4ms/step - loss: 0.5497 - mean_squared_error: 0.5497
Epoch 6/100
1/1 [==============================] - 0s 4ms/step - loss: 0.5118 - mean_squared_error: 0.5118
Epoch 7/100
1/1 [==============================] - 0s 5ms/step - loss: 0.4771 - mean_squared_error: 0.4771
Epoch 8/100
1/1 [==============================] - 0s 6ms/step - loss: 0.4455 - mean_squared_error: 0.4455
Epoch 9/100
1/1 [==============================] - 0s 18ms/step - loss: 0.4170 - mean_squared_error: 0.4170
Epoch 10/100
1/1 [================

In [45]:
model.summary()
# broken numbers

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_5 (Dense)              (None, 10)                20        
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 11        
Total params: 31
Trainable params: 31
Non-trainable params: 0
_________________________________________________________________


In [46]:
y = model.predict(x)

In [47]:
y

array([[0.11859248],
       [0.19123855],
       [0.26388434],
       [0.33653045],
       [0.40917653],
       [0.48182225],
       [0.5544684 ],
       [0.62711436],
       [0.69976044],
       [0.7724067 ]], dtype=float32)

In [54]:
# 3 Layer- Fully Connected- Neural Network
layer1 = keras.layers.Dense(2)
layer2 = keras.layers.Dense(3)
layer3 = keras.layers.Dense(1)
model = keras.models.Sequential([layer1, layer2, layer3])
model.compile(loss= keras.losses.mean_squared_error, optimizer='adam', metrics=[keras.metrics.mean_squared_error])

In [55]:
history = model.fit(x, y, epochs=100, verbose=0) # dont show output here
predictions = model.predict(x)
predictions


array([[ 0.1515853 ],
       [-0.0198998 ],
       [-0.19138487],
       [-0.36286998],
       [-0.5343552 ],
       [-0.70584035],
       [-0.87732536],
       [-1.0488104 ],
       [-1.2202955 ],
       [-1.3917807 ]], dtype=float32)

In [56]:
print(model.get_weights())

[array([[-0.78444684, -0.15535395]], dtype=float32), array([0.06308682, 0.07897931], dtype=float32), array([[-0.30243003, -0.3085671 ,  0.47384867],
       [ 0.59335345, -0.95288277, -0.16265014]], dtype=float32), array([ 0.08369388, -0.07753921,  0.08035991], dtype=float32), array([[ 1.1680062 ],
       [-0.23835626],
       [ 0.7156681 ]], dtype=float32), array([0.08209278], dtype=float32)]


In [57]:
# hidden layer
model.layers[1].get_weights()

[array([[-0.30243003, -0.3085671 ,  0.47384867],
        [ 0.59335345, -0.95288277, -0.16265014]], dtype=float32),
 array([ 0.08369388, -0.07753921,  0.08035991], dtype=float32)]

In [72]:
# 3 Layer- Fully Connected- Neural Network
x = [ 2, 1, 0, -1, -2, -1, 0 ,1, 2 , 1 ,0, -1]
y = [ 1, 1, 0, -1 , -1 , -1  ,0, 1, 1, 1 , 0 , -1]
layer1 = keras.layers.Dense(2, activation=tf.nn.relu)
layer2 = keras.layers.Dense(3, activation=tf.nn.relu)
layer3 = keras.layers.Dense(1, activation=tf.nn.relu)
model = keras.models.Sequential([layer1, layer2, layer3])
model.compile(loss= keras.losses.mean_squared_error, optimizer='adam', metrics=[keras.metrics.mean_squared_error])

In [73]:
history = model.fit(x,y, epochs=50)

Epoch 1/50
1/1 [==============================] - 0s 357ms/step - loss: 0.5723 - mean_squared_error: 0.5723
Epoch 2/50
1/1 [==============================] - 0s 4ms/step - loss: 0.5706 - mean_squared_error: 0.5706
Epoch 3/50
1/1 [==============================] - 0s 4ms/step - loss: 0.5688 - mean_squared_error: 0.5688
Epoch 4/50
1/1 [==============================] - 0s 4ms/step - loss: 0.5671 - mean_squared_error: 0.5671
Epoch 5/50
1/1 [==============================] - 0s 5ms/step - loss: 0.5653 - mean_squared_error: 0.5653
Epoch 6/50
1/1 [==============================] - 0s 7ms/step - loss: 0.5636 - mean_squared_error: 0.5636
Epoch 7/50
1/1 [==============================] - 0s 4ms/step - loss: 0.5618 - mean_squared_error: 0.5618
Epoch 8/50
1/1 [==============================] - 0s 7ms/step - loss: 0.5601 - mean_squared_error: 0.5601
Epoch 9/50
1/1 [==============================] - 0s 5ms/step - loss: 0.5583 - mean_squared_error: 0.5583
Epoch 10/50
1/1 [===========================

In [74]:
predictions = model.predict(x)

In [75]:
predictions

array([[0.5613965 ],
       [0.3027574 ],
       [0.04419173],
       [0.00084505],
       [0.00084505],
       [0.00084505],
       [0.04419173],
       [0.3027574 ],
       [0.5613965 ],
       [0.3027574 ],
       [0.04419173],
       [0.00084505]], dtype=float32)

In [76]:
model.layers[1].get_weights()

[array([[ 0.9987311 , -0.94398093, -0.69420123],
        [ 0.02865008, -0.64274204, -0.10597444]], dtype=float32),
 array([0.00181519, 0.        , 0.        ], dtype=float32)]

In [83]:
x = [ 2, 1, 0, -1, -2, -1, 0 ,1, 2 , 1 ,0, -1]
y = [ 1, 1, 0, -1 , -1 , -1  ,0, 1, 1, 1 , 0 , -1]
layer1 = keras.layers.Dense(1, activation=tf.nn.relu)

model = keras.models.Sequential([layer1])
model.compile(loss= keras.losses.mae, optimizer='adam', metrics=[keras.metrics.mean_squared_error])

In [84]:
history = model.fit(x,y,epochs=100, verbose=0)
predictions = model.predict(x)

In [85]:
predictions

array([[2.5785315],
       [1.2392658],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [0.       ],
       [1.2392658],
       [2.5785315],
       [1.2392658],
       [0.       ],
       [0.       ]], dtype=float32)