<a href="https://colab.research.google.com/github/a-forty-two/cog_may_onwards_21/blob/main/Cog_tf_007_conv1D.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Convolution Layer
# ML is anyway Dense-Dense-> weights and biases are generated 
# finer patterns -> treat those patterns as inputs, rather than inputs as-it-is

In [2]:
from keras.models import Sequential
from keras.layers import Dense, Conv1D, Flatten, MaxPooling1D
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.datasets import load_iris
from numpy import unique


In [5]:

iris = load_iris()
X, y = iris.data, iris.target
print(X.shape)

x = X.reshape(X.shape[0], X.shape[1], 1)
print(x.shape)

(150, 4)
(150, 4, 1)


In [7]:
print(X[0]) # petal iris

[5.1 3.5 1.4 0.2]


In [9]:
y[:-5]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:

xtrain, xtest, ytrain, ytest=train_test_split(x, y, test_size=0.15)


In [20]:
from tensorflow import keras
import tensorflow as tf
model = keras.models.Sequential()

In [21]:
model.add(Conv1D(4, 2, activation = tf.nn.relu,input_shape=(4,1)))

In [22]:
# compress the image
model.add(MaxPooling1D())

In [23]:
import tensorflow as tf
model.add(Dense(3, activation = tf.nn.softmax))

In [25]:
model.compile(loss = 'sparse_categorical_crossentropy', 
     optimizer = "adam",               
              metrics = ['accuracy'])

model.fit(xtrain, ytrain, batch_size=16,epochs=1, verbose=0)
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
module_wrapper_3 (ModuleWrap (None, 3, 4)              12        
_________________________________________________________________
module_wrapper_4 (ModuleWrap (None, 1, 4)              0         
_________________________________________________________________
module_wrapper_5 (ModuleWrap (None, 1, 3)              15        
Total params: 27
Trainable params: 27
Non-trainable params: 0
_________________________________________________________________


In [26]:
model.layers[0].get_weights()

[array([[[ 0.11229932,  0.7180648 ,  0.35399598, -0.379118  ]],
 
        [[-0.16595933, -0.63513476, -0.70566744,  0.7436408 ]]],
       dtype=float32),
 array([ 0.0074067 , -0.00745209,  0.0072498 , -0.00727009], dtype=float32)]

In [27]:
pred = model.predict(xtest)
pred_y = pred.argmax(axis=-1)

In [28]:
pred_y[:5]

array([[0],
       [0],
       [0],
       [0],
       [0]])