In [1]:

%tensorflow_version 1.x
import tensorflow as tf
print(tf.__version__)


TensorFlow 1.x selected.
1.15.2


In [2]:
temp = [0.,0.,1.,0.,0.,0.,2.,1.,0.,1.]
values = tf.reshape(temp, [1,1,2,5]) # 1 list-> 1 list -> 2 list -> 5 elements each 
values

<tf.Tensor 'Reshape:0' shape=(1, 1, 2, 5) dtype=float32>

In [5]:
# Directed Acyclic Graph -> Spark, MongoDB,...


In [6]:
# Behind a tf session-> starts -> executes() -> stops()

In [11]:
avgpool = tf.nn.pool(input=values, window_shape=(2,2), pooling_type='AVG', padding='SAME')
maxpool = tf.nn.pool(input=values, window_shape=(2,2), pooling_type='MAX', padding='SAME')

In [12]:
session = tf.Session()
print('Original Data')
print(session.run(values))
print('AvgPool')
print(session.run(avgpool))
print('MaxPool')
print(session.run(maxpool))
session.close()

Original Data
[[[[0. 0. 1. 0. 0.]
   [0. 2. 1. 0. 1.]]]]
AvgPool
[[[[0.  1.  1.  0.  0.5]
   [0.  2.  1.  0.  1. ]]]]
MaxPool
[[[[0. 2. 1. 0. 1.]
   [0. 2. 1. 0. 1.]]]]


In [ ]:
# Image Compression-> most impactful pixels-> max_pool
# Blur Image-> average pooling
# NLP vectors-> average pooling
# sentiment analysis-> average pooling
# strongest sentiment per sentence-> max pooling
