In [1]:
import tensorflow as tf
from tensorflow import keras

In [2]:
x = [ 2, 1, 0, -1, -2, -1, 0 ,1, 2 , 1 ,0, -1] # Analog sine wave input
y = [ 1, 1, 0, -1 , -1 , -1  ,0, 1, 1, 1 , 0 , -1] # digital output
layer1 = keras.layers.Dense(1, activation=tf.nn.relu)
# ReLU=> y=x, if x >0, y=0, if x <=0

model = keras.models.Sequential([layer1])
model.compile(loss= keras.losses.mae, optimizer='adam', metrics=[keras.metrics.mean_squared_error])

In [3]:
model.fit(x,y,epochs=100, verbose=0)
predictions = model.predict(x)
print(predictions)

[[2.7832463]
 [1.3416232]
 [0.       ]
 [0.       ]
 [0.       ]
 [0.       ]
 [0.       ]
 [1.3416232]
 [2.7832463]
 [1.3416232]
 [0.       ]
 [0.       ]]


In [4]:
model.get_weights()
# trainable_params = input_size * output_size + output_size
# 1 X 1 + 1= 2
# regression neural network

[array([[1.4416231]], dtype=float32), array([-0.09999993], dtype=float32)]

In [18]:
x = [ 2, 1, 0, -1, -2, -1, 0 ,1, 2 , 1 ,0, -1] # Analog sine wave input
y = [ 1, 1, 0, -1 , -1 , -1  ,0, 1, 1, 1 , 0 , -1] # digital output
layer1 = keras.layers.Dense(2)
# ReLU=> y=x, if x >0, y=0, if x <=0
# 0 and 1 -> should be 0th position < 1st position, or vice versa 
model = keras.models.Sequential([layer1])
model.compile(loss= keras.losses.mae, optimizer='adam', metrics=[keras.metrics.mean_squared_error])

In [19]:
model.fit(x,y,epochs=100, verbose=0)
predictions = model.predict(x)
#print(predictions)
# First output-> for positives, 1st position-> negative
for prediction in predictions:
  if prediction[0] > prediction[1]:
    print('positive')
  if prediction[0] < prediction[1]:
    print('negative')
  if prediction[0] == prediction[1]:
    print('zero')

positive
positive
zero
negative
negative
negative
zero
positive
positive
positive
zero
negative


In [20]:
predictions[2]

array([-9.650776e-05, -9.650776e-05], dtype=float32)

In [21]:
predictions

array([[-2.0035083e+00, -2.5379686e+00],
       [-1.0018024e+00, -1.2690326e+00],
       [-9.6507763e-05, -9.6507763e-05],
       [ 1.0016093e+00,  1.2688395e+00],
       [ 2.0033152e+00,  2.5377755e+00],
       [ 1.0016093e+00,  1.2688395e+00],
       [-9.6507763e-05, -9.6507763e-05],
       [-1.0018024e+00, -1.2690326e+00],
       [-2.0035083e+00, -2.5379686e+00],
       [-1.0018024e+00, -1.2690326e+00],
       [-9.6507763e-05, -9.6507763e-05],
       [ 1.0016093e+00,  1.2688395e+00]], dtype=float32)

In [22]:
# users provide 2 entities:
# input set -> parameters
# output set [if missing-> unsupervised learning!]
# anything modified by developers-> hyperparameter
# no. of output dimensions-> i was manipulating!
# loss functions, optimizer functions-> i was adjusting 
# EPOCHS-> how many iterations?

In [23]:
xtest = [ -3, -4, -3, -2, -1, 0]

In [24]:
newpredictions = model.predict(xtest)

In [25]:
for prediction in  newpredictions:
  if prediction[0] > prediction[1]:
    print('positive')
  if prediction[0] < prediction[1]:
    print('negative')
  if prediction[0] == prediction[1]:
    print('zero')

negative
negative
negative
negative
negative
zero


In [ ]:
# if binary classification:
# Dense (1)

# for prediction in predictions:
#   if prediction < 0.5:
#         print('pos')
#   else:
#         print ('neg')

In [36]:
x = [ 2, 1, 0, -1, -2, -1, 0 ,1, 2 , 1 ,0, -1] # Analog sine wave input
y = [ 1, 1, 0, -1 , -1 , -1  ,0, 1, 1, 1 , 0 , -1] # digital output
layer1 = keras.layers.Dense(1, activation = tf.nn.tanh)
# tanh=> from -1 to +1 
model = keras.models.Sequential([layer1])
model.compile(loss= keras.losses.categorical_crossentropy, optimizer='adam')

In [37]:
predictions = model.predict(x)
predictions

array([[ 0.9780645],
       [ 0.8094534],
       [ 0.       ],
       [-0.8094534],
       [-0.9780645],
       [-0.8094534],
       [ 0.       ],
       [ 0.8094534],
       [ 0.9780645],
       [ 0.8094534],
       [ 0.       ],
       [-0.8094534]], dtype=float32)

In [40]:
for prediction in predictions:
  if prediction > 0:
    print ('pos')
  if prediction < 0:
    print ('neg')
  if prediction == 0:
    print ('zero')

pos
pos
zero
neg
neg
neg
zero
pos
pos
pos
zero
neg


In [29]:
# ReLU-> y =  x if x>0, y=0 if x<=0 
# SoftMax-> probab distribution => sum(all_elements) = 1
# TanH-> -1 to 1
# tan => pi/2-> inf and -pi/2-> inf
# tanh-> tan -> 90 deg rotation 
# tanh -> pi/2 and -pi/2 -> 1 and -1 respectively
#        x axis takes infinity!

In [41]:
# tanh scaled b/w 0 to 1
# Probability-> Sigmoid
x = [ 2, 1, 0, -1, -2, -1, 0 ,1, 2 , 1 ,0, -1] # Analog sine wave input
y = [ 1, 1, 0, -1 , -1 , -1  ,0, 1, 1, 1 , 0 , -1] # digital output
layer1 = keras.layers.Dense(1, activation = tf.nn.sigmoid)
# tanh=> from -1 to +1 
model = keras.models.Sequential([layer1])
model.compile(loss= keras.losses.categorical_crossentropy, optimizer='adam')

In [42]:
predictions = model.predict(x)
predictions

array([[0.27167416],
       [0.37917003],
       [0.5       ],
       [0.62083   ],
       [0.72832584],
       [0.62083   ],
       [0.5       ],
       [0.37917003],
       [0.27167416],
       [0.37917003],
       [0.5       ],
       [0.62083   ]], dtype=float32)

In [44]:
for prediction in predictions:
  if prediction < 0.5:
    print ('pos')
  if prediction > 0.5:
    print ('neg')
  if prediction == 0.5:
    print ('zero')

pos
pos
zero
neg
neg
neg
zero
pos
pos
pos
zero
neg


In [ ]:
# normalization
# my general guideline!
# probability (distribution/multi-classification)-> softmax 
# profit/loss/comparisons-> tanh
# regressions/color/no-neg nos. allowed-> ReLU
# binary classification -> sigmoid 

check your model with and w/o relu, whatever works best for you!
